project:
  type: website

website:
  title: "Accelerometer Processing Workshop"
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/tarensanders
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Motivation-and-Behaviour/accel-processing-workshop
          - text: Report a Bug
            url:  https://github.com/Motivation-and-Behaviour/accel-processing-workshop/issues
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - slides.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
  revealjs: 
    theme: simple
    incremental: true
