project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Accelerometer Processing Workshop"
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/tarensanders
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Motivation-and-Behaviour/accel-processing-workshop
          - text: Report a Bug
            url:  https://github.com/Motivation-and-Behaviour/accel-processing-workshop/issues
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - slides.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
  revealjs: 
    theme: simple
    incremental: true
    preview-links: true
    highlight-style: github
    code-annotations: select
    logo: "https://forms.acu.edu.au/__data/assets/file/0020/2330642/ACU_MASTERBRAND_POS_RGB.svg"
    footer: motivation-and-behaviour.github.io/accel-processing-workshop

